default_platform(:android)

platform :android do
  desc "Compilar APK de Flutter en Release"
  lane :build do
    sh("flutter", "pub", "get") # Asegura dependencias actualizadas
    sh("flutter", "test") # Corre los tests antes de compilar (opcional)
    sh("flutter", "build", "apk", "--release") # Build Flutter APK Release
  end
end
