name: Flutter Build CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.2"

    - name: Install Fastlane
      run: sudo gem install fastlane -NV

    - name: Run Fastlane Build
      run: fastlane android build

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')  #crea Release si es push de tag
      uses: softprops/action-gh-release@v2
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }} 
